In [1]:
from hi import sum
sum()

8


In [2]:
import numpy as np
a=np.array((1,2,3,4,5))
print(a)

[1 2 3 4 5]


In [3]:
import numpy as np
a=np.array((1,2,3,4,5))
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
array_2d=[
    [1,2,3],
    [4,5,6],
    [7,8,9]

]
total_sum=0
for row in array_2d:
    for element in row:
        total_sum +=element
print("the sum is",(total_sum))

the sum is 45


In [5]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
total_sum=0
for row in array_2d:
    for element in row:
        total_sum +=element
print("the sum is",(total_sum))

the sum is 45


In [17]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[9,8,7]])
print(a)
print(b)
np.add(a,b)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [9 8 7]]


array([[ 2,  4,  6],
       [13, 13, 13]])

In [18]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[9,8,7]])
print(a)
print(b)
np.subtract(a,b)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [9 8 7]]


array([[ 0,  0,  0],
       [-5, -3, -1]])

In [19]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[9,8,7]])
print(a)
print(b)
np.divide(a,b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [9 8 7]]


array([[1.        , 1.        , 1.        ],
       [0.44444444, 0.625     , 0.85714286]])

In [20]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[9,8,7]])
print(a)
print(b)
np.multiply(a,b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [9 8 7]]


array([[ 1,  4,  9],
       [36, 40, 42]])